# Generated by Django 2.2.17 on 2021-03-24 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=11)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('ReserveDate', models.DateField(default=datetime.date(2021, 3, 24))),
                ('ReserveTime', models.TimeField(null=True)),
                ('NoOfPeople', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Size', models.CharField(choices=[('1', 'one person'), ('2', 'two person'), ('3', 'family')], max_length=2)),
                ('Price', models.IntegerField()),
                ('ImageFood', models.ImageField(upload_to='Images')),
                ('PreparationTime', models.SmallIntegerField(help_text='please enter time based on minutes')),
                ('SpecialFood', models.BooleanField(default=False)),
                ('FCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RestaurantApp.FoodCategory')),
            ],
        ),
    ]
